accent = "#2e7de9"
cursor = "#3760bf"
foreground = "#3760bf"
background = "#e5e6ec"
selection_foreground = "#3760bf"
selection_background = "#b7c1e3"

color0 = "#a1a6c5"
color1 = "#f52a65"
color2 = "#587539"
color3 = "#8c6c3e"
color4 = "#2e7de9"
color5 = "#9854f1"
color6 = "#007197"
color7 = "#6172b0"
color8 = "#8990b3"
color9 = "#f52a65"
color10 = "#587539"
color11 = "#b15c00"
color12 = "#2e7de9"
color13 = "#9854f1"
color14 = "#007197"
color15 = "#3760bf"
